# Generated by Django 5.2.9 on 2026-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etmdevice',
            name='mosambee_tid',
            field=models.CharField(blank=True, help_text='Holds the terminal ID assigned by mosambee to each ETM device', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etmdevice',
            name='allocation_status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('DealerPool', 'Dealer Pool'), ('Allocated', 'Allocated')], db_index=True, default='Stock', max_length=20),
        ),
        migrations.AddIndex(
            model_name='etmdevice',
            index=models.Index(fields=['company', 'palmtec_id'], name='etm_device_company_9fe998_idx'),
        ),
    ]
