# Generated by Django 5.2.9 on 2026-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0002_etmdevice_mosambee_tid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tripdata',
            name='uniq_trip_data',
        ),
        migrations.AddConstraint(
            model_name='tripdata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'company_code', 'schedule_no', 'trip_no', 'start_date'), name='uniq_trip_data'),
        ),
    ]
