# Generated by Django 5.2.9 on 2026-06-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0003_fix_trip_data_unique_constraint_add_schedule_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='TicketAppB.vehicletype'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='conductor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_transactions', to='TicketAppB.employee'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_transactions', to='TicketAppB.employee'),
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(condition=models.Q(('unique_code__isnull', False)), fields=('palmtec_id', 'unique_code'), name='uniq_device_unique_code'),
        ),
    ]
