# Generated by Django 5.2.9 on 2026-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0004_transactiondata_bus_id_transactiondata_conductor_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_unique_code',
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'unique_code'), name='uniq_device_unique_code'),
        ),
    ]
