# Generated by Django 5.2.9 on 2026-06-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0007_settings_and_profile_password_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='crew_check',
        ),
        migrations.RemoveField(
            model_name='settingsprofile',
            name='crew_check',
        ),
    ]
