# Generated by Django 5.2.9 on 2026-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0008_remove_crew_check_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mosambee_merchant_id',
            field=models.CharField(blank=True, help_text='Mosambee merchant ID assigned to this company', max_length=50, null=True),
        ),
    ]
