import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Hand-written (not autogenerated): renames Mosambee-specific identifiers to
    generic "aggregator" naming. Uses RenameModel/RenameField/AlterModelTable
    exclusively so existing rows in mosambee_transaction / mosambee_payout_callback
    and the mosambee_tid / mosambee_merchant_id columns are preserved, not dropped.
    """

    dependencies = [
        ('TicketAppB', '0009_add_mosambee_merchant_id_to_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MosambeeTransaction',
            new_name='AggregatorTransaction',
        ),
        migrations.RenameModel(
            old_name='MosambeePayoutCallback',
            new_name='AggregatorPayoutCallback',
        ),
        migrations.AlterModelTable(
            name='aggregatortransaction',
            table='aggregator_transaction',
        ),
        migrations.AlterModelTable(
            name='aggregatorpayoutcallback',
            table='aggregator_payout_callback',
        ),
        migrations.AlterModelOptions(
            name='aggregatortransaction',
            options={
                'ordering': ['-transaction_datetime'],
                'verbose_name': 'Payment Aggregator Transaction',
                'verbose_name_plural': 'Payment Aggregator Transactions',
            },
        ),
        migrations.AlterModelOptions(
            name='aggregatorpayoutcallback',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Payment Aggregator Payout Callback',
                'verbose_name_plural': 'Payment Aggregator Payout Callbacks',
            },
        ),
        migrations.RenameField(
            model_name='aggregatortransaction',
            old_name='response_sent_to_mosambee',
            new_name='response_sent_to_aggregator',
        ),
        migrations.AlterField(
            model_name='aggregatortransaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_aggregator_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aggregatortransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregator_transactions', to='TicketAppB.company'),
        ),
        migrations.AlterField(
            model_name='aggregatorpayoutcallback',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregator_payout_callbacks', to='TicketAppB.company'),
        ),
        migrations.RenameField(
            model_name='company',
            old_name='mosambee_merchant_id',
            new_name='aggregator_merchant_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='aggregator_merchant_id',
            field=models.CharField(blank=True, help_text='Payment aggregator merchant ID assigned to this company', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='etmdevice',
            old_name='mosambee_tid',
            new_name='aggregator_tid',
        ),
        migrations.AlterField(
            model_name='etmdevice',
            name='aggregator_tid',
            field=models.CharField(blank=True, help_text='Holds the terminal ID assigned by the payment aggregator to each ETM device', max_length=20, null=True, unique=True),
        ),
    ]
