# Generated by Django 5.2.9 on 2026-07-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0010_rename_mosambee_to_aggregator'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__transac_7a7a7e_idx',
            old_name='mosambee_tr_transac_8ac57b_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__transac_e01f2f_idx',
            old_name='mosambee_tr_transac_f1268a_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__verific_d33a6e_idx',
            old_name='mosambee_tr_verific_3ac527_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__verific_a793ef_idx',
            old_name='mosambee_tr_verific_2658ef_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__process_878399_idx',
            old_name='mosambee_tr_process_fe94ad_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__reconci_1a1ced_idx',
            old_name='mosambee_tr_reconci_678a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__invoice_c2f84c_idx',
            old_name='mosambee_tr_invoice_de5ea6_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__transac_04dc50_idx',
            old_name='mosambee_tr_transac_492061_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__settlem_9f07a9_idx',
            old_name='mosambee_tr_settlem_2f9560_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__merchan_af5718_idx',
            old_name='mosambee_tr_merchan_8016e3_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__respons_174fee_idx',
            old_name='mosambee_tr_respons_5d7729_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__is_chec_8c22c6_idx',
            old_name='mosambee_tr_is_chec_10302f_idx',
        ),
        migrations.RenameIndex(
            model_name='aggregatortransaction',
            new_name='aggregator__transac_2782d4_idx',
            old_name='mosambee_tr_transac_89e4a6_idx',
        ),
    ]
