# Generated by Django 5.2.9 on 2026-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0012_rename_mosambee_constraints_to_aggregator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='student',
        ),
        migrations.RemoveField(
            model_name='route',
            name='use_stop',
        ),
        migrations.AlterField(
            model_name='route',
            name='conc',
            field=models.BooleanField(default=False, help_text='Allow concession'),
        ),
    ]
