# Generated by Django 5.2.9 on 2026-07-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0013_remove_route_student_use_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='city',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='state',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='zip_code',
        ),
    ]
