# Generated by Django 5.2.9 on 2026-07-09 11:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_device_fk(apps, schema_editor):
    """Match each SettingsProfile to its ETMDevice via (company, palmtec_id)."""
    SettingsProfile = apps.get_model('TicketAppB', 'SettingsProfile')
    ETMDevice = apps.get_model('TicketAppB', 'ETMDevice')

    for profile in SettingsProfile.objects.all():
        device = ETMDevice.objects.filter(
            company_id=profile.company_id,
            palmtec_id=profile.palmtec_id,
        ).first()
        if device:
            profile.device_id = device.id
            profile.save(update_fields=['device'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0014_remove_depot_city_state_zip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settingsprofile',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='settingsprofile',
            name='device',
            field=models.OneToOneField(blank=True, help_text='The device this profile is configured for. One profile per device.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_profile', to='TicketAppB.etmdevice'),
        ),
        migrations.RunPython(backfill_device_fk, noop_reverse),
        migrations.AlterField(
            model_name='settingsprofile',
            name='palmtec_id',
            field=models.PositiveIntegerField(help_text='Mirrors device.palmtec_id at save time. Not independently client-writable.'),
        ),
        migrations.AlterUniqueTogether(
            name='settingsprofile',
            unique_together={('company', 'name'), ('company', 'palmtec_id')},
        ),
        migrations.AddConstraint(
            model_name='etmdevice',
            constraint=models.UniqueConstraint(fields=('company', 'palmtec_id'), name='uniq_etmdevice_company_palmtec_id'),
        ),
    ]
