# Generated by Django 5.2.9 on 2026-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0015_settingsprofile_device_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='etmdevice',
            name='nfi',
            field=models.CharField(blank=True, help_text='Unique NFI identifier assigned to the device.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etmdevice',
            name='upi',
            field=models.CharField(blank=True, help_text='Unique UPI identifier assigned to the device.', max_length=30, null=True, unique=True),
        ),
    ]
