# Generated by Django 5.2.9 on 2026-07-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0016_etmdevice_nfi_etmdevice_upi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etmdevice',
            name='nfi',
        ),
        migrations.RemoveField(
            model_name='etmdevice',
            name='upi',
        ),
    ]
