# Generated by Django 5.2.9 on 2026-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0017_remove_etmdevice_nfi_remove_etmdevice_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
