# Generated by Django 5.2.9 on 2026-09-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0018_usersession_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web_desktop', 'Web Desktop'), ('web_mobile', 'Web Mobile'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_session',
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_session_user_id_f0e68a_idx')],
            },
        ),
    ]
