# Generated by Django 5.2.9 on 2026-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0019_fcmsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='RS.', max_length=10),
        ),
    ]
