# Generated by Django 5.2.9 on 2026-09-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0020_alter_settings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='Rs.', max_length=10),
        ),
    ]
