# Generated by Django 5.2.9 on 2026-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0021_alter_settings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
