# Generated by Django 5.2.9 on 2026-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0022_alter_settings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='basic_user_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='basic_user_count',
            field=models.IntegerField(default=0),
        ),
    ]
