# Generated by Django 5.2.9 on 2026-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0023_company_basic_user_count_dealer_basic_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='pass_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
