# Generated by Django 5.2.9 on 2026-09-23 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0026_trip_data_unique_with_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allocated_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_users', to='TicketAppB.etmdevice'),
        ),
    ]
