# Generated by Django 5.2.9 on 2026-09-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0027_customuser_allocated_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
