# Generated by Django 5.2.9 on 2026-09-29 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0028_dealer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='getInspectorReport?fn=InspRpt', max_length=100)),
                ('raw_payload', models.TextField(blank=True, default='', help_text='Original raw pipe-delimited payload received from device')),
                ('unique_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('palmtec_id', models.CharField(db_index=True, max_length=50)),
                ('inspector_id', models.CharField(db_index=True, max_length=7)),
                ('schedule_no', models.PositiveIntegerField()),
                ('trip_no', models.PositiveIntegerField()),
                ('direction', models.PositiveSmallIntegerField(choices=[(0, 'UP'), (1, 'DOWN')])),
                ('stage_name', models.CharField(max_length=150)),
                ('inspection_date', models.DateField(db_index=True)),
                ('inspection_time', models.TimeField()),
                ('passengers_in_bus', models.PositiveIntegerField(default=0)),
                ('trip_collection', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bus_no', models.CharField(db_index=True, max_length=30)),
                ('driver', models.CharField(blank=True, default='', max_length=100)),
                ('conductor', models.CharField(blank=True, default='', max_length=100)),
                ('battery_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('checksum', models.CharField(db_index=True, help_text='Checksum appended by the modem', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='TicketAppB.company')),
                ('route_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='TicketAppB.route')),
            ],
            options={
                'db_table': 'bus_inspections',
                'ordering': ['-inspection_date', '-inspection_time'],
                'indexes': [models.Index(fields=['bus_no', 'inspection_date'], name='inspection_bus_date_idx'), models.Index(fields=['route_id', 'inspection_date'], name='inspection_route_date_idx'), models.Index(fields=['inspector_id', 'inspection_date'], name='inspection_inspector_date_idx'), models.Index(fields=['palmtec_id', 'inspection_date'], name='inspection_palmtec_date_idx')],
            },
        ),
    ]
