# Generated by Django 5.2.9 on 2026-09-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0029_businspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='TicketAppB.vehicletype'),
        ),
    ]
