# Generated by Django 5.2.9 on 2026-09-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0030_customuser_assigned_bus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_ticket_datetime',
        ),
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='uniq_device_unique_code',
        ),
    ]
