# Generated by Django 5.2.9 on 2026-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketAppB', '0031_remove_transactiondata_uniq_device_ticket_datetime_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'unique_code', 'company_code', 'ticket_number', 'ticket_date', 'ticket_time'), name='uniq_device_ticket_datetime'),
        ),
        migrations.AddConstraint(
            model_name='transactiondata',
            constraint=models.UniqueConstraint(fields=('palmtec_id', 'unique_code'), name='uniq_device_unique_code'),
        ),
    ]
